### ISSUE TITLE
[Bug]: The game crashed whilst ticking entity Missing required parameters 1.20.1-forge-47.0.18

### ISSUE THREAD

**Issue by OBS3SS1ON** [someaddons/HostileVillages#28]
### Describe the bug you're experiencing

[latest.log](https://github.com/someaddons/HostileVillages/files/11841109/latest.log)

1.20.1-forge-47.0.18

### Reproducability

I hit some illagers and the game threw that error on new world

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/OBS3SS1ON/dd647df100317f15212b18c1109009cd

**Comment by someaddons** [comment]
its a bug of the reseource chickens mod:
```
Caused by: java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>, <parameter minecraft:this_entity>]
	at net.minecraft.world.level.storage.loot.LootParams$Builder.m_287235_(LootParams.java:132) ~[client-1.20.1-20230612.114412-srg.jar%23372!/:?]
	at wallywhip.resourcechickens.entities.ResourceChickenEntity.m_7625_(ResourceChickenEntity.java:606) ~[ResourceChickens-1.20.1-beta1.jar%23349!/:1.20.1-beta1]
	at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1364) ~[client-1.20.1-20230612.114412-srg.jar%23372!/:?]

```
